name: Docker image CI

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set version
        run: |
          echo "VERSION=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_ENV
          echo "Version: $(date +%Y.%-m.%-d.%-H%M)"

      - name: Tag commit
        run: |
          git tag v$VERSION ${{ github.sha }}
          git push origin v$VERSION
            
      - name: Docker login
        run: docker login -u renesackers -p ${{ secrets.DOCKER_HUB }}
        
      - name: Build the Docker image
        run: docker build ./src/ -t renesackers/teslacamplayer:$VERSION -t renesackers/teslacamplayer:latest
        
      - name: Push docker image
        run: docker push --all-tags renesackers/teslacamplayer